name: CASLab@Yonsei
description: Computer Architecture and Systems Laboratory at Yonsei University
url: https://caslab-yonsei.github.io

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "ghp_deploy.sh"
  - vendor/
  - tmp/