- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Yonsei University"
  url: "https://www.yonsei.ac.kr/"
  title: "Yonsei University"

- name: "Systems Semiconductor Engineering"
  url: "https://system.yonsei.ac.kr/"
  title: "Dept. of Systems Semiconductor Engineering"
