name: Jekyll Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js (required for Less compilation)
      - name: Install Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      # Build the site in the jekyll/builder container
      - name: Build Jekyll site using Docker
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && npm install less && bundle install && jekyll build --future"

      # Verify if the _site directory was successfully built
      - name: Verify Jekyll Build Output
        run: |
          if [ ! -d "_site" ]; then
            echo "Jekyll build failed! _site directory not found."
            exit 1

      # Optional: Upload _site as an artifact to inspect the build result
      - name: Upload Jekyll build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jekyll-build
          path: _site
