name: Test Jekyll Build

on:
  # Trigger the workflow on pull request to main branch
  pull_request:
    branches: ["main"]

  # You can also manually trigger it
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "/test-build"
        env:
          JEKYLL_ENV: production

      - name: Confirm successful build
        run: echo "Jekyll build was successful!"
